name: Update GitHub Contributions

on:
  workflow_dispatch:  # Allows manual run from GitHub Actions tab
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  push:
    branches:
      - master   # Update this when you push-to-master

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo (manoj-malviya-96.github.io)
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: manoj-malviya-96/manoj-malviya-96.github.io  # Explicitly specify the repo

      # Fetch GitHub Contributions data for the username 'manoj-malviya-96'
      - name: Fetch GitHub Contributions
        run: |
          curl -H "Authorization: token ${{ secrets.WEBSITE_TOKEN }}" \
          https://api.github.com/users/manoj-malviya-96/events \
          -o _data/contributions.json

      # Commit and push the updated contributions.json file to the repository
      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add _data/contributions.json
          git commit -m "Update contributions data"
          git push
