name: Update GitHub Contributions

on:
  workflow_dispatch:  # Allows manual run from GitHub Actions tab
  schedule:
    - cron: '0 0 */7 * *'  # Runs every 7 days at midnight UTC
  push:
    branches:
      - master  # Replace with gh-pages if needed for GitHub Pages branch

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo (manoj-malviya-96.github.io)
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: manoj-malviya-96/manoj-malviya-96.github.io
          persist-credentials: false  # Prevents conflicts with the next authentication step

      # Set up the GitHub token for authentication
      - name: Setup GitHub token
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.WEBSITE_TOKEN }}@github.com/manoj-malviya-96/manoj-malviya-96.github.io.git

      # Fetch GitHub Contributions data for the username 'manoj-malviya-96'
      - name: Fetch GitHub Contributions
        run: |
          curl -H "Authorization: token ${{ secrets.WEBSITE_TOKEN }}" \
          https://api.github.com/users/manoj-malviya-96/events \
          -o _data/contributions.json

      # Commit and push the updated contributions.json file to the repository
      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add _data/contributions.json
          git commit -m "Update contributions data"
          git push origin master  # Push to the correct branch
